// marks/ → data.gen.ts: every mark as an inline data url, so no consumer ever waits on a file request
// (chords' daemon stalls one behind /api/stats). logo.ts runs this after each write.
import { readFileSync, writeFileSync } from 'node:fs';
import { extname, join } from 'node:path';

const here = import.meta.dirname;
const manifest = JSON.parse(
    readFileSync(join(here, 'marks', 'logos.json'), 'utf8'),
) as Record<string, { theme?: 'light' | 'dark' }>;

const dataUrl = (type: string, bytes: Buffer | string) =>
    `data:${type};base64,${Buffer.from(bytes).toString('base64')}`;

const marks: Record<string, { light?: string; dark?: string }> = {};
for (const [file, spec] of Object.entries(manifest)) {
    const bytes = readFileSync(join(here, 'marks', file));
    const isDark = spec.theme === 'dark';
    const name = file.replace(/(-dark)?\.(svg|png)$/, '');
    marks[name] ??= {};
    const mark = marks[name];
    if (extname(file) === '.png') {
        mark.light = dataUrl('image/png', bytes);
        continue;
    }
    const svg = bytes.toString('utf8');
    // a one-colour mark draws in currentColor, which an <img> resolves to black: bake a white copy for dark
    if (svg.includes('currentColor')) {
        mark.light = dataUrl(
            'image/svg+xml',
            svg.replaceAll('currentColor', '#000'),
        );
        mark.dark = dataUrl(
            'image/svg+xml',
            svg.replaceAll('currentColor', '#fff'),
        );
        continue;
    }
    mark[isDark ? 'dark' : 'light'] = dataUrl('image/svg+xml', svg);
}

const lines = Object.entries(marks)
    .sort(([a], [z]) => a.localeCompare(z))
    .map(
        ([name, mark]) =>
            `    ${JSON.stringify(name)}: ${JSON.stringify(mark)},`,
    );
writeFileSync(
    join(here, 'data.gen.ts'),
    `// generated by build.ts from marks/logos.json — rerun it, never edit this file\nexport const logos = {\n${lines.join('\n')}\n} as const;\n`,
);
console.log(`logos: ${lines.length} marks → data.gen.ts`);
